// Carousel Pets Data
export let petCollection = [{
    id: `0`,
    name: "GIANT PANDAS",
    location: "Native to Southwest China",
    image: "/assets/images/pandas.png",
    meal: "/assets/icons/banana-bamboo_icon.svg",
},
{
    id: `1`,
    name: "EAGLES",
    location: "Native to South America",
    image: "/assets/images/eagle.png",
    meal: "/assets/icons/meet-fish_icon.svg",
},
{
    id: `2`,
    name: "GORILLAS",
    location: "Native to Congo",
    image: "/assets/images/gorilla.png",
    meal: "/assets/icons/banana-bamboo_icon.svg",
},
{
    id: `3`,
    name: "TWO-TOED SLOTH",
    location: "Mesoamerica, South America",
    image: "/assets/images/sloth.png",
    meal: "/assets/icons/banana-bamboo_icon.svg",
},
{
    id: `4`,
    name: "CHEETAHS",
    location: "Native to Africa",
    image: "/assets/images/cheetahs.png",
    meal: "/assets/icons/meet-fish_icon.svg",
},
{
    id: `5`,
    name: "PENGUINS",
    location: "Native to Antarctica",
    image: "/assets/images/penguin.png",
    meal: "/assets/icons/meet-fish_icon.svg",
},

{
    id: `6`,
    name: "FOX",
    location: "all of Europe",
    image: "/assets/images/fox.jpg",
    meal: "/assets/icons/meet-fish_icon.svg",
},
{
    id: `7`,
    name: "HYENA",
    location: "Native to Africa",
    image: "/assets/images/hyena (1).jpg",
    meal: "/assets/icons/meet-fish_icon.svg",
},
{
    id: `8`,
    name: "KENGURU",
    location: "Native to Australia",
    image: "/assets/images/kenguru.jpg",
    meal: "/assets/icons/banana-bamboo_icon.svg",
},
{
    id: `9`,
    name: "OWL",
    location: "Native to Europe",
    image: "/assets/images/owl.jpg",
    meal: "/assets/icons/meet-fish_icon.svg",
},
{
    id: `10`,
    name: "PUMA",
    location: "Native to America",
    image: "/assets/images/puma.jpg",
    meal: "/assets/icons/meet-fish_icon.svg",
},
{
    id: `11`,
    name: "WOLF",
    location: "Native to Europe",
    image: "/assets/images/wolf.jpg",
    meal: "/assets/icons/meet-fish_icon.svg",
},
{
    id: `12`,
    name: "ALLIGATORS",
    location: "Native to Southeastern U.S.",
    image: "/assets/images/alligators.png",
    meal: "/assets/icons/meet-fish_icon.svg",
},
];
