export let testimonials = [{
    id: "0",
    name: "Oskar Samborsky",
    location: "Local Austria",
    lastVisit: "Yesterday",
    quote: " Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals. The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.",
    logo: "./assets/images/person1.png",
},
{
    id: "1",
    name: "Mila Riksha",
    location: "Local Austria",
    lastVisit: "Yesterday",
    quote: "My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.",
    logo: "./assets/images/person2.png",
},
{
    id: "2",
    name: "John Spicker",
    location: "Germanu",
    lastVisit: "Today",
    quote: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar,",
    logo: "./assets/images/person3.png",
},
{
    id: "3",
    name: "Bob Dirt",
    location: "USA",
    lastVisit: "2 days ago",
    quote: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas",
    logo: "./assets/images/person1.png",
},
{
    id: "4",
    name: "Andjei Lastowski",
    location: "Poland",
    lastVisit: "Today",
    quote: "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles. Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan lingues. It va esser tam simplic quam Occidental in fact, it va esser Occidental. A un Angleso it va semblar un simplificat Angles, quam un skeptic Cambridge amico dit me que Occidental es.Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica,",
    logo: "./assets/images/person2.png",
},
{
    id: "5",
    name: "Marshall Branson",
    location: "SAR",
    lastVisit: "Yesterday",
    quote: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum dolore quo, sunt commodi praesentium earum eaque assumenda nam ratione hic officiis obcaecati, alias repudiandae incidunt, ipsa modi quisquam unde aut eius. Maiores blanditiis veniam odit voluptate quae obcaecati dolores nobis laboriosam iure minus, cupiditate quibusdam ipsum saepe libero debitis error soluta fugiat totam earum voluptas ad quos. Officiis quia unde modi dicta deleniti hic, quod fugit sequi natus cumque, laboriosam eum saepe quae eius voluptatum aliquam facere quas totam porro perspiciatis accusamus quam maiores quibusdam eveniet. Itaque neque quos quis perferendis, facilis eum dolor non saepe, iusto et obcaecati ex dignissimos provident? Natus, consectetur. Quisquam cupiditate optio eaque nemo impedit nulla quam, beatae numquam sequi maiores assumenda reiciendis et atque tempora error sed obcaecati quo quia voluptas vitae unde autem?",
    logo: "./assets/images/person2.png",
},
{
    id: "6",
    name: "Fredericka Michelin",
    location: "Local Austria",
    lastVisit: "Yesterday",
    quote: "The best online zoo I’ve met. The best online zoo I’ve met. The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals. Ullam labore, error architecto sapiente nam quisquam aperiam doloremque temporibus molestiae asperiores iusto, consequuntur ut? Aspernatur iure ex natus, quam molestias, nostrum optio doloribus architecto, vitae dolor quaerat quae laboriosam numquam dignissimos laudantium eum quas id voluptate nesciunt minus! Fugiat est pariatur soluta aliquam quaerat eum illo esse adipisci. Veniam perspiciatis eius beatae architecto ratione officiis qui quaerat ea fugiat nobis nihil maiores debitis corrupti vero blanditiis, asperiores quasi accusantium!",
    logo: "./assets/images/person3.png",
},
{
    id: "7",
    name: "Ammy Grey",
    location: "Canada",
    lastVisit: "3 days ago",
    quote: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas",
    logo: "./assets/images/person1.png",
},
{
    id: "8",
    name: "Dirk Shtanzen",
    location: "Germany",
    lastVisit: "Yesterday",
    quote: " Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar,",
    logo: "./assets/images/person2.png",
},
{
    id: "9",
    name: "Michael John",
    location: "Local Austria",
    lastVisit: "Today",
    quote: "he best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals. The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals in the forest.",
    logo: "./assets/images/person3.png",
},
{
    id: "10",
    name: "Taras Savko",
    location: "Ukrain",
    lastVisit: "Today",
    quote: "Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself",
    logo: "./assets/images/person1.png",
},
];